pyweb/posts/urls.py
# from django.contrib import admin
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.post_list_v,name="list"),
    path('<slug:slug>',views.post_page,name="page"),
]

pyweb/pyweb/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.about),
    path('post/',include('posts.urls'))
]

pyweb/posts/models.py
from django.db import models
# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=75)
    body=models.TextField()
    slug=models.SlugField()
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

pyweb/posts/views.py
from django.shortcuts import render
from .models import Post
# from django.http import HttpResponse

def post_list_v(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'post_/post_list.html', {'posts': posts})


def post_page(request,slug):
    # return HttpResponse(slug)
    posts = Post.objects.get(slug=slug)
    return render(request, 'post_/post_page.html', {'posts': posts})

pyweb/pyweb/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    # return HttpResponse("My homepage : this is the message from httpResponse in 'homepage' View.py")
    # return HttpResponse("this is the homepage")
    return render(request, 'home.html')


def about(request):
    # return HttpResponse("My About page : this is the message from httpResponse in 'about' View.py") 
    return render(request,'about.html')

pyweb/posts/templates/post_/post_list.html
{% extends "basic.html" %}
{% block title %}POST{% endblock %}
{% block upper_descritipon %}
<section>
  <h1>the html is working</h1>
  {% for post in posts %}
  <article class ="postdata">
    <h2>
      <a class="slug" href = "{% url 'posts:page' slug=post.slug%}">
        {{ post.title }}
      </a>
    </h2>
    <p>{{ post.date }}</p>
    <p>{{ post.body }}</p>
  </article>
  {% endfor %}
</section>
{% endblock %}

pyweb/posts/templates/post_/post_page.html
{% extends "basic.html" %}

{% block title %} 
    {{ post.title }} 
{% endblock %}

{% block upper_descritipon %}
    <section>
        <h1>{{ post.title }}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p> 
    </section>
{% endblock %}

pyweb/templates/about.html
{% extends "basic.html" %}
{% block title %}About{% endblock %}
{% block upper_descritipon %}
  <h1>the html is working in about.html</h1>
{% endblock %}

pyweb/templates/basic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} django app {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <nav>
      <a href="/">Home</a>| <a href="/about">About</a>|
      <a href="{% url 'posts:list' %}">Post</a>
    </nav>
    <main>{% block upper_descritipon %} top descritipon {% endblock %}</main>
  </body>
</html>

pyweb/templates/home.html
{% extends "basic.html" %}
{% block title %}HOME{% endblock %}
{% block upper_descritipon %}
  <h1>the html is working in home.html</h1>
{% endblock %}